### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fire** [uasi/rwkv-in-150-lines-ex#1]
Can you write a license for this?

I am from the Godot Engine community, so I would prefer MIT or Apache2 license.

* https://github.com/godotengine/godot/blob/master/LICENSE.txt (MIT)
* https://github.com/BlinkDL/RWKV-LM/blob/main/LICENSE (Apache2)

**Comment by uasi** [comment]
@fire sure, now licensed under Apache 2.0!

**Comment by fire** [comment]
Thanks
